export const GET_ASSESSMENTS_LOADING = 'GET_ASSESSMENTS_LOADING'
export const GET_ASSESSMENTS_SUCCESS = 'GET_ASSESSMENTS_SUCCESS'
export const GET_ASSESSMENTS_FAIL = 'GET_ASSESSMENTS_FAIL'

export const GET_ASSESSMENT_LOADING = 'GET_ASSESSMENT_LOADING'
export const GET_ASSESSMENT_SUCCESS = 'GET_ASSESSMENT_SUCCESS'
export const GET_ASSESSMENT_FAIL = 'GET_ASSESSMENT_FAIL'

export const GET_ASSESSMENT_BY_SUBJECT_LOADING = 'GET_ASSESSMENT_BY_SUBJECT_LOADING'
export const GET_ASSESSMENT_BY_SUBJECT_SUCCESS = 'GET_ASSESSMENT_BY_SUBJECT_SUCCESS'
export const GET_ASSESSMENT_BY_SUBJECT_FAIL = 'GET_ASSESSMENT_BY_SUBJECT_FAIL'

export const CREATE_ASSESSMENT_LOADING = 'CREATE_ASSESSMENT_LOADING'
export const CREATE_ASSESSMENT_SUCCESS = 'CREATE_ASSESSMENT_SUCCESS'
export const CREATE_ASSESSMENT_FAIL = 'CREATE_ASSESSMENT_FAIL'

export const ADD_QUESTION_LOADING = 'ADD_QUESTION_LOADING'
export const ADD_QUESTION_SUCCESS = 'ADD_QUESTION_SUCCESS'
export const ADD_QUESTION_FAIL = 'ADD_QUESTION_FAIL'