export const TEACHER_LOGIN_LOADING = 'TEACHER_LOGIN_LOADING'
export const TEACHER_LOGIN_FAIL = 'TEACHER_LOGIN_FAIL'
export const TEACHER_LOGIN_SUCCESS = 'TEACHER_LOGIN_SUCCESS'

export const STUDENT_LOGIN_LOADING = 'STUDENT_LOGIN_LOADING'
export const STUDENT_LOGIN_FAIL = 'STUDENT_LOGIN_FAIL'
export const STUDENT_LOGIN_SUCCESS = 'STUDENT_LOGIN_SUCCESS'

export const USER_LOGOUT = 'USER_LOGOUT'