export const GET_SCHOOLS_LOADING = 'GET_SCHOOLS_LOADING'
export const GET_SCHOOLS_SUCCESS = 'GET_SCHOOLS_SUCCESS'
export const GET_SCHOOLS_FAIL = 'GET_SCHOOLS_FAIL'

export const GET_SCHOOL_LOADING = 'GET_SCHOOL_LOADING'
export const GET_SCHOOL_SUCCESS = 'GET_SCHOOL_SUCCESS'
export const GET_SCHOOL_FAIL = 'GET_SCHOOL_FAIL'


export const CREATE_SCHOOL_LOADING = 'CREATE_SCHOOL_LOADING'
export const CREATE_SCHOOL_SUCCESS = 'CREATE_SCHOOL_SUCCESS'
export const CREATE_SCHOOL_FAIL = 'CREATE_SCHOOL_FAIL'