export const GET_STUDENTS_LOADING = 'GET_STUDENTS_LOADING'
export const GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS'
export const GET_STUDENTS_FAIL = 'GET_STUDENTS_FAIL'

export const GET_STUDENT_LOADING = 'GET_STUDENT_LOADING'
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS'
export const GET_STUDENT_FAIL = 'GET_STUDENT_FAIL'

export const CREATE_STUDENT_LOADING = 'CREATE_STUDENT_LOADING'
export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS'
export const CREATE_STUDENT_FAIL = 'CREATE_STUDENT_FAIL'

export const UPDATE_STUDENT_LOADING = 'UPDATE_STUDENT_LOADING'
export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
export const UPDATE_STUDENT_FAIL = 'UPDATE_STUDENT_FAIL'