export const GET_SUBJECTS_LOADING = 'GET_SUBJECTS_LOADING'
export const GET_SUBJECTS_SUCCESS = 'GET_SUBJECTS_SUCCESS'
export const GET_SUBJECTS_FAIL = 'GET_SUBJECTS_FAIL'

export const GET_SUBJECT_LOADING = 'GET_SUBJECT_LOADING'
export const GET_SUBJECT_SUCCESS = 'GET_SUBJECT_SUCCESS'
export const GET_SUBJECT_FAIL = 'GET_SUBJECT_FAIL'

export const GET_SUBJECT_BY_NAME_LOADING = 'GET_SUBJECT_BY_NAME_LOADING'
export const GET_SUBJECT_BY_NAME_SUCCESS = 'GET_SUBJECT_BY_NAME_SUCCESS'
export const GET_SUBJECT_BY_NAME_FAIL = 'GET_SUBJECT_BY_NAME_FAIL'
export const GET_SUBJECT_BY_NAME_RESET = 'GET_SUBJECT_BY_NAME_RESET'

export const CREATE_SUBJECT_LOADING = 'CREATE_SUBJECT_LOADING'
export const CREATE_SUBJECT_SUCCESS = 'CREATE_SUBJECT_SUCCESS'
export const CREATE_SUBJECT_FAIL = 'CREATE_SUBJECT_FAIL'
