export const GET_TEACHERS_LOADING = 'GET_TEACHERS_LOADING'
export const GET_TEACHERS_SUCCESS = 'GET_TEACHERS_SUCCESS'
export const GET_TEACHERS_FAIL = 'GET_TEACHERS_FAIL'

export const GET_TEACHER_LOADING = 'GET_TEACHER_LOADING'
export const GET_TEACHER_SUCCESS = 'GET_TEACHER_SUCCESS'
export const GET_TEACHER_FAIL = 'GET_TEACHER_FAIL'

export const CREATE_TEACHER_LOADING = 'CREATE_TEACHER_LOADING'
export const CREATE_TEACHER_SUCCESS = 'CREATE_TEACHER_SUCCESS'
export const CREATE_TEACHER_FAIL = 'CREATE_TEACHER_FAIL'

export const UPDATE_TEACHER_LOADING = 'UPDATE_TEACHER_LOADING'
export const UPDATE_TEACHER_SUCCESS = 'UPDATE_TEACHER_SUCCESS'
export const UPDATE_TEACHER_FAIL = 'UPDATE_TEACHER_FAIL'